networks: 
  springappnetwork: 
    external: true
services: 
  mongo: 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb123
    image: mongo
    networks: 
      - springappnetwork
    restart: always
    volumes: 
      - "mongodb:/data/db"
  springboot: 
    depends_on: 
      - mongo
    deploy: 
      replicas: 2
      restart_policy: 
        condition: on-failure
        delay: 10s
        max_attempts: 5
      update_config: 
        delay: 20s
        parallelism: 1
    environment: 
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb123
    image: "dockerlegendroy/spring-boot-mongo:latest"
    networks: 
      - springappnetwork
    ports: 
      - "8555:8080"
    restart: always
    working_dir: /opt/app
version: "3.1"
volumes: 
  mongodb: 
    external: true
    
    
 
   
